package io.github.darealturtywurty.turtybot.util;

import java.text.DateFormat;
import java.util.HashSet;
import java.util.Random;
import java.util.Set;
import java.util.logging.Logger;
import java.util.regex.Pattern;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.typesafe.config.Config;
import com.typesafe.config.ConfigFactory;

import io.github.darealturtywurty.turtybot.managers.levelling_system.LevellingManager;

public final class Constants {

	public static final long DEFAULT_OWNER_ID = 309776610255437824L;

	public static final String USER_AGENT = "Mozilla/5.0 | TurtyBot#8108 | TurtyWurty#5690";
	public static final Pattern URL_PATTERN = Pattern.compile(
			"(?:^|[\\W])((ht|f)tp(s?):\\/\\/|www\\.)" + "(([\\w\\-]+\\.){1,}?([\\w\\-.~]+\\/?)*"
					+ "[\\p{Alnum}.,%_=?&#\\-+()\\[\\]\\*$~@!:/{};']*)",
			Pattern.CASE_INSENSITIVE | Pattern.MULTILINE | Pattern.DOTALL);
	public static final Gson GSON = new GsonBuilder().setPrettyPrinting().create();
	public static final Config CONFIG = ConfigFactory.load();
	public static final Logger LOGGER = Logger.getGlobal();

	public static final DateFormat DATE_FORMAT = DateFormat.getInstance();

	public static final Random RANDOM = new Random();

	public static final Set<String> FILE_EXTENSIONS = new HashSet<>();

	public static final double MILLI_TO_MONTH = 2.628e+9;

	public static final LevellingManager LEVELLING_MANAGER = new LevellingManager();

	public static final String BEAN_DUMPY_URL = "https://images-ext-2.discordapp.net/external/hFKX8jvrVZ_MobmGXB5IHiWCCejb8T-Q-so6T414k50/https/media.discordapp.net/attachments/855162784924434442/859517109725954048/dumpy.gif";

	static {
		FILE_EXTENSIONS.add("txt");
		FILE_EXTENSIONS.add("log");
		FILE_EXTENSIONS.add("java");
		FILE_EXTENSIONS.add("kt");
		FILE_EXTENSIONS.add("cs");
		FILE_EXTENSIONS.add("cpp");
		FILE_EXTENSIONS.add("py");
		FILE_EXTENSIONS.add("asp");
		FILE_EXTENSIONS.add("css");
		FILE_EXTENSIONS.add("html");
		FILE_EXTENSIONS.add("js");
		FILE_EXTENSIONS.add("php");
		FILE_EXTENSIONS.add("xml");
		FILE_EXTENSIONS.add("conf");
		FILE_EXTENSIONS.add("json");
		FILE_EXTENSIONS.add("toml");
		FILE_EXTENSIONS.add("doc");
		FILE_EXTENSIONS.add("docx");
		FILE_EXTENSIONS.add("as");
		FILE_EXTENSIONS.add("applescript");
		FILE_EXTENSIONS.add("ino");
		FILE_EXTENSIONS.add("asciidoc");
		FILE_EXTENSIONS.add("asc");
		FILE_EXTENSIONS.add("adoc");
		FILE_EXTENSIONS.add("asm");
		FILE_EXTENSIONS.add("bat");
		FILE_EXTENSIONS.add("cmd");
		FILE_EXTENSIONS.add("b");
		FILE_EXTENSIONS.add("bf");
		FILE_EXTENSIONS.add("c");
		FILE_EXTENSIONS.add("h");
		FILE_EXTENSIONS.add("w");
		FILE_EXTENSIONS.add("cats");
		FILE_EXTENSIONS.add("idc");
		FILE_EXTENSIONS.add("cake");
		FILE_EXTENSIONS.add("cshtml");
		FILE_EXTENSIONS.add("csx");
		FILE_EXTENSIONS.add("c++");
		FILE_EXTENSIONS.add("cc");
		FILE_EXTENSIONS.add("cp");
		FILE_EXTENSIONS.add("cxx");
		FILE_EXTENSIONS.add("h");
		FILE_EXTENSIONS.add("h++");
		FILE_EXTENSIONS.add("hh");
		FILE_EXTENSIONS.add("hpp");
		FILE_EXTENSIONS.add("hxx");
		FILE_EXTENSIONS.add("inc");
		FILE_EXTENSIONS.add("inl");
		FILE_EXTENSIONS.add("ipp");
		FILE_EXTENSIONS.add("tcc");
		FILE_EXTENSIONS.add("tpp");
		FILE_EXTENSIONS.add("cmake");
		FILE_EXTENSIONS.add("csv");
		FILE_EXTENSIONS.add("clj");
		FILE_EXTENSIONS.add("boot");
		FILE_EXTENSIONS.add("coffee");
		FILE_EXTENSIONS.add("d");
		FILE_EXTENSIONS.add("di");
		FILE_EXTENSIONS.add("dart");
		FILE_EXTENSIONS.add("dockerfile");
		FILE_EXTENSIONS.add("e");
		FILE_EXTENSIONS.add("fs");
		FILE_EXTENSIONS.add("fsi");
		FILE_EXTENSIONS.add("fsx");
		FILE_EXTENSIONS.add("gd");
		FILE_EXTENSIONS.add("glsl");
		FILE_EXTENSIONS.add("fp");
		FILE_EXTENSIONS.add("frag");
		FILE_EXTENSIONS.add("frg");
		FILE_EXTENSIONS.add("fsh");
		FILE_EXTENSIONS.add("fshader");
		FILE_EXTENSIONS.add("geo");
		FILE_EXTENSIONS.add("geom");
		FILE_EXTENSIONS.add("glslv");
		FILE_EXTENSIONS.add("gshader");
		FILE_EXTENSIONS.add("shader");
		FILE_EXTENSIONS.add("vert");
		FILE_EXTENSIONS.add("vrx");
		FILE_EXTENSIONS.add("vsh");
		FILE_EXTENSIONS.add("vshader");
		FILE_EXTENSIONS.add("go");
		FILE_EXTENSIONS.add("properties");
		FILE_EXTENSIONS.add("gradle");
		FILE_EXTENSIONS.add("classpath");
		FILE_EXTENSIONS.add("gitattributes");
		FILE_EXTENSIONS.add("gitignore");
		FILE_EXTENSIONS.add("project");
		FILE_EXTENSIONS.add("groovy");
		FILE_EXTENSIONS.add("hlsl");
		FILE_EXTENSIONS.add("htm");
		FILE_EXTENSIONS.add("http");
		FILE_EXTENSIONS.add("ini");
		FILE_EXTENSIONS.add("prefs");
		FILE_EXTENSIONS.add("pro");
		FILE_EXTENSIONS.add("lock");
		FILE_EXTENSIONS.add("bbmodel");
		FILE_EXTENSIONS.add("json5");
		FILE_EXTENSIONS.add("jade");
		FILE_EXTENSIONS.add("ktm");
		FILE_EXTENSIONS.add("kts");
		FILE_EXTENSIONS.add("scala");
		FILE_EXTENSIONS.add("lol");
		FILE_EXTENSIONS.add("lua");
		FILE_EXTENSIONS.add("rbxs");
		FILE_EXTENSIONS.add("m");
		FILE_EXTENSIONS.add("md");
		FILE_EXTENSIONS.add("markdown");
		FILE_EXTENSIONS.add("mkd");
		FILE_EXTENSIONS.add("mkdown");
		FILE_EXTENSIONS.add("matlab");
		FILE_EXTENSIONS.add("org");
		FILE_EXTENSIONS.add("pas");
		FILE_EXTENSIONS.add("pp");
		FILE_EXTENSIONS.add("ps1");
		FILE_EXTENSIONS.add("psd1");
		FILE_EXTENSIONS.add("spm1");
		FILE_EXTENSIONS.add("raw");
		FILE_EXTENSIONS.add("rb");
		FILE_EXTENSIONS.add("ruby");
		FILE_EXTENSIONS.add("rs");
		FILE_EXTENSIONS.add("sql");
		FILE_EXTENSIONS.add("cql");
		FILE_EXTENSIONS.add("ddl");
		FILE_EXTENSIONS.add("db2");
		FILE_EXTENSIONS.add("sh");
		FILE_EXTENSIONS.add("bash");
		FILE_EXTENSIONS.add("swift");
		FILE_EXTENSIONS.add("fr");
		FILE_EXTENSIONS.add("nb");
		FILE_EXTENSIONS.add("ncl");
		FILE_EXTENSIONS.add("no");
		FILE_EXTENSIONS.add("textfile");
		FILE_EXTENSIONS.add("ts");
		FILE_EXTENSIONS.add("tsx");
		FILE_EXTENSIONS.add("anim");
		FILE_EXTENSIONS.add("asset");
		FILE_EXTENSIONS.add("mat");
		FILE_EXTENSIONS.add("meta");
		FILE_EXTENSIONS.add("prefab");
		FILE_EXTENSIONS.add("unity");
		FILE_EXTENSIONS.add("uc");
		FILE_EXTENSIONS.add("vb");
		FILE_EXTENSIONS.add("vbs");
		FILE_EXTENSIONS.add("vba");
		FILE_EXTENSIONS.add("vue");
		FILE_EXTENSIONS.add("ant");
		FILE_EXTENSIONS.add("csproj");
		FILE_EXTENSIONS.add("csprject");
		FILE_EXTENSIONS.add("yml");
		FILE_EXTENSIONS.add("yaml");
		FILE_EXTENSIONS.add("desktop");
		FILE_EXTENSIONS.add("wisp");
		FILE_EXTENSIONS.add("mcmeta");
		FILE_EXTENSIONS.add("txt");
		FILE_EXTENSIONS.add("log");
		FILE_EXTENSIONS.add("java");
		FILE_EXTENSIONS.add("kt");
		FILE_EXTENSIONS.add("cs");
		FILE_EXTENSIONS.add("cpp");
		FILE_EXTENSIONS.add("py");
		FILE_EXTENSIONS.add("asp");
		FILE_EXTENSIONS.add("css");
		FILE_EXTENSIONS.add("html");
		FILE_EXTENSIONS.add("js");
		FILE_EXTENSIONS.add("php");
		FILE_EXTENSIONS.add("xml");
		FILE_EXTENSIONS.add("conf");
		FILE_EXTENSIONS.add("json");
		FILE_EXTENSIONS.add("toml");
		FILE_EXTENSIONS.add("doc");
		FILE_EXTENSIONS.add("docx");
		FILE_EXTENSIONS.add("as");
		FILE_EXTENSIONS.add("applescript");
		FILE_EXTENSIONS.add("ino");
		FILE_EXTENSIONS.add("asciidoc");
		FILE_EXTENSIONS.add("asc");
		FILE_EXTENSIONS.add("adoc");
		FILE_EXTENSIONS.add("asm");
		FILE_EXTENSIONS.add("bat");
		FILE_EXTENSIONS.add("cmd");
		FILE_EXTENSIONS.add("b");
		FILE_EXTENSIONS.add("bf");
		FILE_EXTENSIONS.add("c");
		FILE_EXTENSIONS.add("h");
		FILE_EXTENSIONS.add("w");
		FILE_EXTENSIONS.add("cats");
		FILE_EXTENSIONS.add("idc");
		FILE_EXTENSIONS.add("cake");
		FILE_EXTENSIONS.add("cshtml");
		FILE_EXTENSIONS.add("csx");
		FILE_EXTENSIONS.add("c++");
		FILE_EXTENSIONS.add("cc");
		FILE_EXTENSIONS.add("cp");
		FILE_EXTENSIONS.add("cxx");
		FILE_EXTENSIONS.add("h");
		FILE_EXTENSIONS.add("h++");
		FILE_EXTENSIONS.add("hh");
		FILE_EXTENSIONS.add("hpp");
		FILE_EXTENSIONS.add("hxx");
		FILE_EXTENSIONS.add("inc");
		FILE_EXTENSIONS.add("inl");
		FILE_EXTENSIONS.add("ipp");
		FILE_EXTENSIONS.add("tcc");
		FILE_EXTENSIONS.add("tpp");
		FILE_EXTENSIONS.add("cmake");
		FILE_EXTENSIONS.add("csv");
		FILE_EXTENSIONS.add("clj");
		FILE_EXTENSIONS.add("boot");
		FILE_EXTENSIONS.add("coffee");
		FILE_EXTENSIONS.add("d");
		FILE_EXTENSIONS.add("di");
		FILE_EXTENSIONS.add("dart");
		FILE_EXTENSIONS.add("dockerfile");
		FILE_EXTENSIONS.add("e");
		FILE_EXTENSIONS.add("fs");
		FILE_EXTENSIONS.add("fsi");
		FILE_EXTENSIONS.add("fsx");
		FILE_EXTENSIONS.add("gd");
		FILE_EXTENSIONS.add("glsl");
		FILE_EXTENSIONS.add("fp");
		FILE_EXTENSIONS.add("frag");
		FILE_EXTENSIONS.add("frg");
		FILE_EXTENSIONS.add("fsh");
		FILE_EXTENSIONS.add("fshader");
		FILE_EXTENSIONS.add("geo");
		FILE_EXTENSIONS.add("geom");
		FILE_EXTENSIONS.add("glslv");
		FILE_EXTENSIONS.add("gshader");
		FILE_EXTENSIONS.add("shader");
		FILE_EXTENSIONS.add("vert");
		FILE_EXTENSIONS.add("vrx");
		FILE_EXTENSIONS.add("vsh");
		FILE_EXTENSIONS.add("vshader");
		FILE_EXTENSIONS.add("go");
		FILE_EXTENSIONS.add("properties");
		FILE_EXTENSIONS.add("gradle");
		FILE_EXTENSIONS.add("classpath");
		FILE_EXTENSIONS.add("gitattributes");
		FILE_EXTENSIONS.add("gitignore");
		FILE_EXTENSIONS.add("project");
		FILE_EXTENSIONS.add("groovy");
		FILE_EXTENSIONS.add("hlsl");
		FILE_EXTENSIONS.add("htm");
		FILE_EXTENSIONS.add("http");
		FILE_EXTENSIONS.add("ini");
		FILE_EXTENSIONS.add("prefs");
		FILE_EXTENSIONS.add("pro");
		FILE_EXTENSIONS.add("lock");
		FILE_EXTENSIONS.add("bbmodel");
		FILE_EXTENSIONS.add("json5");
		FILE_EXTENSIONS.add("jade");
		FILE_EXTENSIONS.add("ktm");
		FILE_EXTENSIONS.add("kts");
		FILE_EXTENSIONS.add("scala");
		FILE_EXTENSIONS.add("lol");
		FILE_EXTENSIONS.add("lua");
		FILE_EXTENSIONS.add("rbxs");
		FILE_EXTENSIONS.add("m");
		FILE_EXTENSIONS.add("md");
		FILE_EXTENSIONS.add("markdown");
		FILE_EXTENSIONS.add("mkd");
		FILE_EXTENSIONS.add("mkdown");
		FILE_EXTENSIONS.add("matlab");
		FILE_EXTENSIONS.add("org");
		FILE_EXTENSIONS.add("pas");
		FILE_EXTENSIONS.add("pp");
		FILE_EXTENSIONS.add("ps1");
		FILE_EXTENSIONS.add("psd1");
		FILE_EXTENSIONS.add("spm1");
		FILE_EXTENSIONS.add("raw");
		FILE_EXTENSIONS.add("rb");
		FILE_EXTENSIONS.add("ruby");
		FILE_EXTENSIONS.add("rs");
		FILE_EXTENSIONS.add("sql");
		FILE_EXTENSIONS.add("cql");
		FILE_EXTENSIONS.add("ddl");
		FILE_EXTENSIONS.add("db2");
		FILE_EXTENSIONS.add("sh");
		FILE_EXTENSIONS.add("bash");
		FILE_EXTENSIONS.add("swift");
		FILE_EXTENSIONS.add("fr");
		FILE_EXTENSIONS.add("nb");
		FILE_EXTENSIONS.add("ncl");
		FILE_EXTENSIONS.add("no");
		FILE_EXTENSIONS.add("textfile");
		FILE_EXTENSIONS.add("ts");
		FILE_EXTENSIONS.add("tsx");
		FILE_EXTENSIONS.add("anim");
		FILE_EXTENSIONS.add("asset");
		FILE_EXTENSIONS.add("mat");
		FILE_EXTENSIONS.add("meta");
		FILE_EXTENSIONS.add("prefab");
		FILE_EXTENSIONS.add("unity");
		FILE_EXTENSIONS.add("uc");
		FILE_EXTENSIONS.add("vb");
		FILE_EXTENSIONS.add("vbs");
		FILE_EXTENSIONS.add("vba");
		FILE_EXTENSIONS.add("vue");
		FILE_EXTENSIONS.add("ant");
		FILE_EXTENSIONS.add("csproj");
		FILE_EXTENSIONS.add("csprject");
		FILE_EXTENSIONS.add("yml");
		FILE_EXTENSIONS.add("yaml");
		FILE_EXTENSIONS.add("desktop");
		FILE_EXTENSIONS.add("wisp");
		FILE_EXTENSIONS.add("mcmeta");
		FILE_EXTENSIONS.add("env");
		FILE_EXTENSIONS.add("ignore");
	}

	private Constants() {
	}
}
